version: '3.11'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${PSQL_DB_NAME}
      POSTGRES_USER: ${PSQL_USERNAME}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
    ports:
      - "5433:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  wkhtmltopdf:
    image: openlabs/docker-wkhtmltopdf-aas
    ports:
      - "8080:80"
    volumes:
      - .:/app

  celery:
    environment:
      DOCKER_ENV: true
    volumes:
      - .:/app
      - ./media:/media
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A food_service.celery:app worker --loglevel=info
    depends_on:
      - redis
