# Generated by Django 4.2.4 on 2023-09-01 14:08

from django.db import migrations, models
import django.db.models.deletion
import food.file_path


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PrinterModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("api_key", models.CharField(max_length=256, unique=True)),
                (
                    "check_type",
                    models.CharField(
                        choices=[("client", "Client"), ("kitchen", "Kitchen")]
                    ),
                ),
                ("point_id", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="CheckModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("client", "Client"), ("kitchen", "Kitchen")]
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[
                            ("new", "New"),
                            ("rendered", "Rendered"),
                            ("printed", "Printed"),
                        ],
                        default=0,
                    ),
                ),
                ("order", models.JSONField()),
                (
                    "pdf_file",
                    models.FileField(upload_to=food.file_path.get_pdf_file_path),
                ),
                (
                    "printer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checks",
                        to="food.printermodel",
                    ),
                ),
            ],
        ),
    ]
