# Generated by Django 4.2.4 on 2023-09-01 14:42

from django.db import migrations, models
import food.file_path


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkmodel",
            name="pdf_file",
            field=models.FileField(
                blank=True, null=True, upload_to=food.file_path.get_pdf_file_path
            ),
        ),
    ]
