# Generated by Django 4.2.4 on 2023-09-01 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0002_alter_checkmodel_pdf_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkmodel",
            name="status",
            field=models.SmallIntegerField(
                choices=[
                    ("new", "New"),
                    ("rendered", "Rendered"),
                    ("printed", "Printed"),
                ],
                default="new",
            ),
        ),
    ]
