# Generated by Django 4.2.4 on 2023-09-01 21:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0003_alter_checkmodel_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkmodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("rendered", "Rendered"),
                    ("printed", "Printed"),
                ],
                default="new",
            ),
        ),
    ]
